services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-dev
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`staging.pharminc.in`)