FROM node:alpine

WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Add build arguments for Next.js environment variables
ARG NEXT_PUBLIC_SOCKET_URL
ARG NEXT_PUBLIC_API_AUTH
ARG NEXT_PUBLIC_API_USER
ARG NEXT_PUBLIC_API_NETWORK
ARG NEXT_PUBLIC_API_BACKGROUND
ARG NEXT_PUBLIC_API_INSTITUTE
ARG NEXT_PUBLIC_API_JOB
ARG NEXT_PUBLIC_API_CONTENT
ARG NEXT_PUBLIC_SOCKET_URL_SERVER

# Set environment variables from build arguments
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_SOCKET_URL_SERVER=$NEXT_PUBLIC_SOCKET_URL_SERVER    
ENV NEXT_PUBLIC_API_AUTH=$NEXT_PUBLIC_API_AUTH
ENV NEXT_PUBLIC_API_USER=$NEXT_PUBLIC_API_USER
ENV NEXT_PUBLIC_API_NETWORK=$NEXT_PUBLIC_API_NETWORK
ENV NEXT_PUBLIC_API_BACKGROUND=$NEXT_PUBLIC_API_BACKGROUND
ENV NEXT_PUBLIC_API_INSTITUTE=$NEXT_PUBLIC_API_INSTITUTE
ENV NEXT_PUBLIC_API_JOB=$NEXT_PUBLIC_API_JOB
ENV NEXT_PUBLIC_API_CONTENT=$NEXT_PUBLIC_API_CONTENT

# Build the app
RUN npm run build

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]